SHELL := /bin/bash

COMMANDE1_MSG="✨ Menu ✨"
COMMANDE1_MSG="✨ Lancement de l'application✨"
COMMANDE2_MSG="✨ Initialisation de la session de Brainstormoming✨ "
COMMANDE3_MSG="✨ brainstorming generation d idées ✨"
COMMANDE4_MSG="✨ Initialisation du chatbot✨"
COMMANDE5_MSG="✨ Initialisation du Prompt Model"
COMMANDE6_MSG="🏗 Factory Generate Howto 📜 ✨"
COMMANDE7_MSG="🏗 Factory Start Building composant 📦 ✨"
COMMANDE8_MSG="🏗 Factory running Compose page 📦 ✨"
COMMANDE9_MSG="✨ Mise à jour du repertoire sur github✨"
COMMANDEU_CTF="✨ Mise à jour du repertoire sur github✨"
COMMANDE10_MSG="✨Exit session✨"
menuIA_MSG="✨ Menu ✨"
menu_CTD_MSG="✨ Menu ✨"
howto_MSG="✨howto✨"
gemini_MSG="✨Test F2✨"
neoFs_MSG="✨Initialisation du neoFS✨"
worker_MSG="✨Initialisation du Worker -ia ✨"
gpt_MSG="✨Initialisation de GPT ✨"


# Ajoutez une règle pour chaque commande

commandeR:
	@echo "${COMMANDE2_MSG}"
	@./menu.sh

android:
	@echo "${menuIA_MSG}"
	@node wow/android/Android_Pibot.js

ia:
	@echo "${menuIA_MSG}"
	@./intro.sh

commande1:
	@echo "${COMMANDE2_MSG}"
	@npm run start

commande2:
	@echo "${COMMANDE2_MSG}"
	@./intro.sh
map:
	@echo "${COMMANDE4_MSG}"
	@npm run start items/mapascii/

commande3:
	@echo "${COMMANDE3_MSG}"
	@node .setup/brainstorming.js

commande4:
	@echo "${COMMANDE4_MSG}"
	@node .setup/chatCompletion.js

commande5:
	@echo "${COMMANDE5_MSG}"
	@node .setup/myprompt.js

howto:
	@echo "${howto_MSG}"
	@node .setup/howto.js

commande7:
	@echo "${COMMANDE5_MSG}"
	@node build/Composants.js

commande8:
	@echo "${COMMANDE5_MSG}"
	@node src/app/composer.js

update:
	@echo "${Update_MSG}"
	@git add .
	@git commit -m "Update"
	@git push
	@echo "✨ Mise à jour terminée✨"

commande10:
	@echo "${COMMANDE10_MSG}"

gemini:
	@echo "${gemini_MSG}"
	@node models/gemini/Gemini_Pibot.js

neofs:
	@echo "${neoFs_MSG}"
	@node data/neofs/neoFs_Pibot

gpt:
	@echo "${gpt_MSG}"
	@node models/openai/gpt-io.js

avatars:
	@echo "${avatars_MSG}"
	@node Public/Avatars_Pibot.js

worker:
	@echo "${worker_MSG}"
	@node workspace/worker_Pibot.js
gem:
	@echo "${gem_MSG}"
	@node models/Gem_Pibot/Gem_bot.js

groq:
	@echo "${groq_MSG}"
	@node auto/models/groq/groq_Pibot.js

commandeY:
	@echo "${blog_MSG}"
	@node blog/blog_Pibot.js

commandeU:
	@echo "${COMMANDEU_MSG}"
	@node user/user_Pibot.js


commandeM:
	@echo "${COMMANDEM_MSG}"
	@node data/meta_Pibot.js

tasks:
	@node .setup/role.mjs showTasks

# Tâche Make pour ajouter une tâche
add-task:
	@node .setup/role.mjs addTask $(task)


menu :
	@echo "Welcom To cycliq Economical system."
	@echo""
	@echo"╔═════════════════════════════════════╗     ╔═════════════════════════════════════════════════════════════════════╗"
	@echo"╠═══════════ ✨ Pi Console ═══════════╣     ║  [💫] [💬] [📚] [🌌] [✨] [⚡️] [💰] [🌴] [📱] [📡]              [🛰]║"
	@echo"║                                     ║     ╠═════════════════════════════════════════════════════════════════════╣"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"║                                     ║     ║                                                                     ║"
	@echo"╠═════════════════════════════════════╣     ╠═════════════════════════════════════════════════════════════════════╣"
	@echo"║(∏)                                  ║     ║[💻.📱]:/<                                                        /%>║"
	@echo"╚═════════════════════════════════════╝     ╚═════════════════════════════════════════════════════════════════════╝"	
	@echo""

MAGIC_TARGETS := codex build rep file script clean

all: $(MAGIC_TARGETS)

srv : run start

start:
	@npm start

run:
	@node ./srv/srv.js

gitC:
	@echo "✨ Mise en état du dossier sur github✨"
	@git add .
	@git commit -m "Connection"
	@git push
	@echo "✨ Mise à jour terminée✨"
S1:
	@echo "✨ Mrun session brainstorming ✨"
	@git add .
	@git commit -m "sesssion brainstorm"
	@git push
	@echo "✨ Mise à jour terminée✨"

.PHONY: sh commande1 commande2 commande3 commande4 commande5